In [1]:
import torch
import numpy as np

In [4]:
x = torch.rand(4,3,3)
print(x)

tensor([[[0.9050, 0.3540, 0.6077],
         [0.2938, 0.4979, 0.6032],
         [0.2939, 0.7888, 0.7903]],

        [[0.6739, 0.3650, 0.3219],
         [0.7885, 0.8281, 0.3186],
         [0.3577, 0.0480, 0.3021]],

        [[0.1994, 0.1901, 0.1965],
         [0.0636, 0.6601, 0.6305],
         [0.7175, 0.1582, 0.9808]],

        [[0.6060, 0.5826, 0.0882],
         [0.5793, 0.8865, 0.7987],
         [0.3143, 0.2101, 0.8677]]])


In [5]:
torch.manual_seed(12)


In [6]:
torch.manual_seed(12)
x = torch.rand(4, 4, 4)
print (x)

tensor([[[0.4657, 0.2328, 0.4527, 0.5871],
         [0.4086, 0.1272, 0.6373, 0.2421],
         [0.7312, 0.7224, 0.1992, 0.6948],
         [0.5830, 0.6318, 0.5559, 0.1262]],

        [[0.9790, 0.8443, 0.1256, 0.4456],
         [0.6601, 0.0554, 0.1573, 0.8137],
         [0.7216, 0.2717, 0.3003, 0.6099],
         [0.5784, 0.6083, 0.4339, 0.8813]],

        [[0.3216, 0.2604, 0.2566, 0.1872],
         [0.6423, 0.1786, 0.1435, 0.7490],
         [0.7275, 0.1641, 0.3273, 0.1239],
         [0.6138, 0.4535, 0.7659, 0.1800]],

        [[0.3338, 0.9526, 0.8919, 0.9859],
         [0.6348, 0.8811, 0.9391, 0.1173],
         [0.1342, 0.9405, 0.6803, 0.5556],
         [0.8713, 0.0782, 0.8578, 0.7540]]])


In [7]:
#resize a tensor
y = x.view(-1, 8)
print(y)
print(y.size())

tensor([[0.4657, 0.2328, 0.4527, 0.5871, 0.4086, 0.1272, 0.6373, 0.2421],
        [0.7312, 0.7224, 0.1992, 0.6948, 0.5830, 0.6318, 0.5559, 0.1262],
        [0.9790, 0.8443, 0.1256, 0.4456, 0.6601, 0.0554, 0.1573, 0.8137],
        [0.7216, 0.2717, 0.3003, 0.6099, 0.5784, 0.6083, 0.4339, 0.8813],
        [0.3216, 0.2604, 0.2566, 0.1872, 0.6423, 0.1786, 0.1435, 0.7490],
        [0.7275, 0.1641, 0.3273, 0.1239, 0.6138, 0.4535, 0.7659, 0.1800],
        [0.3338, 0.9526, 0.8919, 0.9859, 0.6348, 0.8811, 0.9391, 0.1173],
        [0.1342, 0.9405, 0.6803, 0.5556, 0.8713, 0.0782, 0.8578, 0.7540]])
torch.Size([8, 8])


In [89]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [93]:
a = 2
a*= 5
print(a)

10
