In [1]:
import torch
import numpy as np

In [2]:
x = torch.rand(4,3,3)
print(x)

tensor([[[0.1965, 0.4965, 0.1833],
         [0.7627, 0.9546, 0.8809],
         [0.4081, 0.0289, 0.7712]],

        [[0.2510, 0.7097, 0.4705],
         [0.9002, 0.9173, 0.5195],
         [0.1766, 0.4781, 0.5703]],

        [[0.7263, 0.8700, 0.8447],
         [0.3065, 0.2086, 0.7337],
         [0.7443, 0.0801, 0.4875]],

        [[0.3394, 0.5110, 0.4432],
         [0.9106, 0.7989, 0.3024],
         [0.7932, 0.5793, 0.1245]]])


In [5]:
torch.manual_seed(12)


In [6]:
torch.manual_seed(12)
x = torch.rand(4, 4, 4)
print (x)

tensor([[[0.4657, 0.2328, 0.4527, 0.5871],
         [0.4086, 0.1272, 0.6373, 0.2421],
         [0.7312, 0.7224, 0.1992, 0.6948],
         [0.5830, 0.6318, 0.5559, 0.1262]],

        [[0.9790, 0.8443, 0.1256, 0.4456],
         [0.6601, 0.0554, 0.1573, 0.8137],
         [0.7216, 0.2717, 0.3003, 0.6099],
         [0.5784, 0.6083, 0.4339, 0.8813]],

        [[0.3216, 0.2604, 0.2566, 0.1872],
         [0.6423, 0.1786, 0.1435, 0.7490],
         [0.7275, 0.1641, 0.3273, 0.1239],
         [0.6138, 0.4535, 0.7659, 0.1800]],

        [[0.3338, 0.9526, 0.8919, 0.9859],
         [0.6348, 0.8811, 0.9391, 0.1173],
         [0.1342, 0.9405, 0.6803, 0.5556],
         [0.8713, 0.0782, 0.8578, 0.7540]]])


In [7]:
#resize a tensor
y = x.view(-1, 8)
print(y)
print(y.size())

tensor([[0.4657, 0.2328, 0.4527, 0.5871, 0.4086, 0.1272, 0.6373, 0.2421],
        [0.7312, 0.7224, 0.1992, 0.6948, 0.5830, 0.6318, 0.5559, 0.1262],
        [0.9790, 0.8443, 0.1256, 0.4456, 0.6601, 0.0554, 0.1573, 0.8137],
        [0.7216, 0.2717, 0.3003, 0.6099, 0.5784, 0.6083, 0.4339, 0.8813],
        [0.3216, 0.2604, 0.2566, 0.1872, 0.6423, 0.1786, 0.1435, 0.7490],
        [0.7275, 0.1641, 0.3273, 0.1239, 0.6138, 0.4535, 0.7659, 0.1800],
        [0.3338, 0.9526, 0.8919, 0.9859, 0.6348, 0.8811, 0.9391, 0.1173],
        [0.1342, 0.9405, 0.6803, 0.5556, 0.8713, 0.0782, 0.8578, 0.7540]])
torch.Size([8, 8])


In [89]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [93]:
a = 2
a*= 5
print(a)

10
